[package]
name = "csv-to-sqlmodel"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
csv = "1.3.1"
rand = "0.8.5"
rayon = "1.10.0"
regex = "1.11.1"
tempfile = "3.14.0"
uuid = { version = "1.0", features = ["v4"] }
